# Generated by Django 3.1.1 on 2020-09-27 22:06

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import positions.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.SlugField(max_length=40)),
                ('color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=140)),
                ('icon', models.CharField(max_length=20)),
                ('position', positions.fields.PositionField(default=-1)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stories.stage')),
            ],
        ),
    ]
