# Generated by Django 3.1.1 on 2020-09-27 22:16

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(max_length=140),
        ),
    ]
