# Generated by Django 3.1.1 on 2020-09-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200928_0133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='icon',
            field=models.ImageField(null=True, upload_to='story-icons'),
        ),
    ]
